#!/usr/bin/env bash

set -euo pipefail

if ! command -v taskset >/dev/null 2>&1; then
    echo "taskset is required to constrain each run to a real CPU allocation" >&2
    exit 1
fi

cpu_counts=${TREETOP_PERF_CPU_COUNTS:-1,2,4,8}
cpu_sets=${TREETOP_PERF_CPU_SETS:-}
layouts=${TREETOP_PERF_LAYOUTS:-default}
output_dir=${TREETOP_PERF_OUTPUT_DIR:-performance-results}

expand_cpu_spec() {
    local spec=$1
    local range start end cpu
    local ranges=()
    expanded_cpus=()
    IFS=',' read -r -a ranges <<< "${spec}"
    for range in "${ranges[@]}"; do
        range=${range//[[:space:]]/}
        if [[ ${range} =~ ^[0-9]+-[0-9]+$ ]]; then
            start=${range%-*}
            end=${range#*-}
            if (( start > end )); then
                return 1
            fi
            for ((cpu = start; cpu <= end; cpu++)); do
                expanded_cpus+=("${cpu}")
            done
        elif [[ ${range} =~ ^[0-9]+$ ]]; then
            expanded_cpus+=("${range}")
        else
            return 1
        fi
    done
    (( ${#expanded_cpus[@]} > 0 ))
}

affinity=$(taskset -pc "$$")
affinity=${affinity##*: }
if ! expand_cpu_spec "${affinity}"; then
    echo "could not determine the process CPU affinity" >&2
    exit 1
fi
available_cpus=("${expanded_cpus[@]}")
declare -A available_cpu_lookup=()
for cpu in "${available_cpus[@]}"; do
    available_cpu_lookup["${cpu}"]=1
done

allocation_counts=()
allocation_lists=()
allocation_slugs=()
if [[ -n ${cpu_sets} ]]; then
    IFS=';' read -r -a requested_sets <<< "${cpu_sets}"
    for requested_set in "${requested_sets[@]}"; do
        requested_set=${requested_set//[[:space:]]/}
        if ! expand_cpu_spec "${requested_set}"; then
            echo "invalid CPU set: ${requested_set}" >&2
            exit 1
        fi
        selected_array=("${expanded_cpus[@]}")
        unset selected_lookup
        declare -A selected_lookup=()
        for cpu in "${selected_array[@]}"; do
            if [[ -z ${available_cpu_lookup["${cpu}"]+present} ]]; then
                echo "CPU ${cpu} from set ${requested_set} is outside current affinity ${affinity}" >&2
                exit 1
            fi
            if [[ -n ${selected_lookup["${cpu}"]+present} ]]; then
                echo "CPU ${cpu} is repeated in set ${requested_set}" >&2
                exit 1
            fi
            selected_lookup["${cpu}"]=1
        done
        selected_cpus=$(IFS=,; echo "${selected_array[*]}")
        allocation_counts+=("${#selected_array[@]}")
        allocation_lists+=("${selected_cpus}")
        allocation_slugs+=("cpus-${selected_cpus//,/_}")
    done
else
    IFS=',' read -r -a requested_counts <<< "${cpu_counts}"
    for count in "${requested_counts[@]}"; do
        count=${count//[[:space:]]/}
        if [[ ! ${count} =~ ^[1-9][0-9]*$ ]]; then
            echo "invalid CPU count: ${count}" >&2
            exit 1
        fi
        if (( count > ${#available_cpus[@]} )); then
            echo "Skipping ${count} CPUs; current affinity provides ${#available_cpus[@]}."
            continue
        fi
        selected_cpus=$(IFS=,; echo "${available_cpus[*]:0:count}")
        allocation_counts+=("${count}")
        allocation_lists+=("${selected_cpus}")
        allocation_slugs+=("${count}cpu")
    done
fi

if (( ${#allocation_counts[@]} == 0 )); then
    echo "no CPU allocations selected" >&2
    exit 1
fi

mkdir -p "${output_dir}"
summary_path="${output_dir}/summary.md"
temporary_output=$(mktemp)
trap 'rm -f "${temporary_output}"' EXIT

{
    echo "# Treetop REST performance matrix"
    echo
    echo "Generated by scripts/run-performance-matrix.sh. Each row is client-observed loopback HTTP timing."
    echo
    echo "| allocated CPUs | CPU affinity | layout | workload | concurrency | requests/s | mean µs | p50 µs | p90 µs | p95 µs | p99 µs | max µs |"
    echo "| ---: | --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"
} > "${summary_path}"

cargo test --release --test latency_characterization --no-run

IFS=',' read -r -a requested_layouts <<< "${layouts}"

for allocation_index in "${!allocation_counts[@]}"; do
    count=${allocation_counts[allocation_index]}
    selected_cpus=${allocation_lists[allocation_index]}
    allocation_slug=${allocation_slugs[allocation_index]}

    for layout in "${requested_layouts[@]}"; do
        layout=${layout//[[:space:]]/}
        workers=
        rayon_threads=
        case "${layout}" in
            default)
                ;;
            http)
                workers=${count}
                rayon_threads=1
                ;;
            batch)
                workers=1
                rayon_threads=${count}
                ;;
            full)
                workers=${count}
                rayon_threads=${count}
                ;;
            *)
                echo "invalid layout '${layout}'; use default, http, batch, or full" >&2
                exit 1
                ;;
        esac

        report_path="${output_dir}/${allocation_slug}-${layout}.json"
        runtime_env=(
            "TREETOP_PERF_OUTPUT=${report_path}"
        )
        if [[ -n ${workers} ]]; then
            runtime_env+=("TREETOP_PERF_WORKERS=${workers}")
        fi
        if [[ -n ${rayon_threads} ]]; then
            runtime_env+=("TREETOP_PERF_RAYON_THREADS=${rayon_threads}")
        fi

        echo
        echo "Running ${count}-CPU/${layout} on CPU list ${selected_cpus}"
        taskset -c "${selected_cpus}" \
            env -u TREETOP_PERF_WORKERS -u TREETOP_PERF_RAYON_THREADS \
            "${runtime_env[@]}" \
            cargo test --release --test latency_characterization -- --ignored --nocapture \
            2>&1 | tee "${temporary_output}"

        awk -v cpus="${count}" -v cpu_set="${selected_cpus}" -v layout="${layout}" '
            /^\| workload \|/ { in_http_table = 1; next }
            /^\| action workload \|/ { exit }
            in_http_table && /^\| ---/ { next }
            in_http_table && /^\|/ {
                line = $0
                sub(/^\| /, "", line)
                print "| " cpus " | " cpu_set " | " layout " | " line
                next
            }
            in_http_table { exit }
        ' "${temporary_output}" >> "${summary_path}"
    done
done

echo
echo "Combined scaling table: ${summary_path}"
echo "Anonymous JSON reports: ${output_dir}/*.json"
